"""Write coil geometry as KiCad S-expression text.

* ``board_text``     a complete stand-alone ``.kicad_pcb`` (KiCad 8 file
                     format, 20240108, which KiCad 8, 9 and 10 open).
* ``terminal_footprint_text``  the ``.kicad_mod`` used for the two
                     terminal bars; the pcbnew front-end loads it with
                     FootprintLoad so it never has to touch the
                     version-specific pad/padstack API.

Blind and buried vias are written with the ``blind`` keyword plus their
layer pair, which is how KiCad 8/9 store both kinds.
"""
from __future__ import annotations

import json
import math
import uuid
from typing import Dict, List, Tuple

from ..geometry import CoilGeometry, Terminal

KICAD8_LAYER_IDS = {"F.Cu": 0, "B.Cu": 31}
TECH_LAYERS = [
    (32, "B.Adhes", "user", "B.Adhesive"), (33, "F.Adhes", "user", "F.Adhesive"),
    (34, "B.Paste", "user", None), (35, "F.Paste", "user", None),
    (36, "B.SilkS", "user", "B.Silkscreen"), (37, "F.SilkS", "user", "F.Silkscreen"),
    (38, "B.Mask", "user", None), (39, "F.Mask", "user", None),
    (40, "Dwgs.User", "user", "User.Drawings"), (41, "Cmts.User", "user", "User.Comments"),
    (42, "Eco1.User", "user", "User.Eco1"), (43, "Eco2.User", "user", "User.Eco2"),
    (44, "Edge.Cuts", "user", None), (45, "Margin", "user", None),
    (46, "B.CrtYd", "user", "B.Courtyard"), (47, "F.CrtYd", "user", "F.Courtyard"),
    (48, "B.Fab", "user", None), (49, "F.Fab", "user", None),
]


def q(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def n(x: float) -> str:
    s = ("%.6f" % x).rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def u() -> str:
    return str(uuid.uuid4())


def copper_layer_names(count: int) -> List[str]:
    return ["F.Cu"] + ["In%d.Cu" % i for i in range(1, count - 1)] + ["B.Cu"]


def strand_net_names(geo: CoilGeometry) -> List[str]:
    p = geo.params
    if p.per_strand_nets:
        return ["%s_S%02d" % (p.net_prefix, s + 1) for s in range(geo.n_strands)]
    return [p.net_prefix] * geo.n_strands


def _terminal_body(t: Terminal, net_clause: str, rel: Tuple[float, float]) -> List[str]:
    ax, ay = rel
    pts = " ".join("(xy %s %s)" % (n(x - ax), n(y - ay)) for x, y in t.polygon)
    out = []
    size = max(t.hole_pad, 0.5)
    out.append('  (pad "1" thru_hole custom (at 0 0) (size %s %s) (drill %s) (layers "*.Cu" "*.Mask")%s'
               % (n(size), n(size), n(t.drill), net_clause))
    out.append('    (options (clearance outline) (anchor circle))')
    out.append('    (primitives (gr_poly (pts %s) (width 0) (fill yes)))' % pts)
    out.append('    (uuid %s))' % q(u()))
    for (hx, hy) in t.holes:
        out.append('  (pad "1" thru_hole circle (at %s %s) (size %s %s) (drill %s) (layers "*.Cu" "*.Mask")%s (uuid %s))'
                   % (n(hx - ax), n(hy - ay), n(t.hole_pad), n(t.hole_pad), n(t.drill), net_clause, q(u())))
    return out


def terminal_footprint_text(t: Terminal, name: str = "LitzTerminal") -> str:
    """Stand-alone footprint (origin at the terminal anchor) for FootprintLoad."""
    lines = ['(footprint %s (version 20240108) (generator "litzgen") (layer "F.Cu")' % q(name),
             '  (descr "Terminal bar of a PCB Litz coil generated by LitzGen")',
             '  (attr board_only exclude_from_pos_files exclude_from_bom)',
             '  (property "Reference" "LT**" (at 0 -2 0) (layer "F.SilkS") (uuid %s) (effects (font (size 1 1) (thickness 0.15))))' % q(u()),
             '  (property "Value" %s (at 0 2 0) (layer "F.Fab") (uuid %s) (effects (font (size 1 1) (thickness 0.15))))' % (q(name), q(u()))]
    lines += _terminal_body(t, "", t.anchor)
    lines.append(")")
    return "\n".join(lines) + "\n"


def board_text(geo: CoilGeometry, outline_margin: float = 5.0, include_params: bool = True) -> str:
    p = geo.params
    st = p.stackup
    ncu = st.n_layers
    cu_names = copper_layer_names(ncu)
    if list(st.kicad_layers) != cu_names:
        # coil may use a subset of a bigger stack: make the board as big as the highest layer
        idx = [int(x[2:-3]) if x.startswith("In") else (0 if x == "F.Cu" else 10 ** 6) for x in st.kicad_layers]
        inner_max = max([i for i in idx if 0 < i < 10 ** 6], default=0)
        cu_names = copper_layer_names(inner_max + 2)
    ids = {name: (0 if name == "F.Cu" else 31 if name == "B.Cu" else int(name[2:-3])) for name in cu_names}
    nets = sorted(set(strand_net_names(geo)))
    net_id = {name: i + 1 for i, name in enumerate(nets)}
    L: List[str] = []
    L.append('(kicad_pcb (version 20240108) (generator "litzgen") (generator_version "1.0")')
    L.append('  (general (thickness %s) (legacy_teardrops no))' % n(st.total_thickness))
    L.append('  (paper "A3")')
    L.append('  (layers')
    for name in cu_names:
        L.append('    (%d %s signal)' % (ids[name], q(name)))
    for lid, name, typ, alias in TECH_LAYERS:
        L.append('    (%d %s %s%s)' % (lid, q(name), typ, (" " + q(alias)) if alias else ""))
    L.append('  )')
    # stackup (only exact when the coil uses every copper layer of the board)
    L.append('  (setup')
    L.append('    (stackup')
    L.append('      (layer "F.SilkS" (type "Top Silk Screen"))')
    L.append('      (layer "F.Mask" (type "Top Solder Mask") (thickness 0.01))')
    diel = list(st.dielectric)
    if len(cu_names) != ncu:
        tot = sum(diel)
        diel = [tot / (len(cu_names) - 1)] * (len(cu_names) - 1)
    for i, name in enumerate(cu_names):
        L.append('      (layer %s (type "copper") (thickness %s))' % (q(name), n(st.copper_thickness)))
        if i < len(cu_names) - 1:
            kind = "core" if i % 2 == 1 else "prepreg"
            L.append('      (layer "dielectric %d" (type %s) (thickness %s) (material "FR4") (epsilon_r 4.5) (loss_tangent 0.02))'
                     % (i + 1, q(kind), n(diel[i])))
    L.append('      (layer "B.Mask" (type "Bottom Solder Mask") (thickness 0.01))')
    L.append('      (layer "B.SilkS" (type "Bottom Silk Screen"))')
    L.append('      (copper_finish "None") (dielectric_constraints no))')
    L.append('    (pad_to_mask_clearance 0)')
    L.append('    (allow_soldermask_bridges_in_footprints no))')
    L.append('  (net 0 "")')
    for name in nets:
        L.append('  (net %d %s)' % (net_id[name], q(name)))
    members: List[str] = []
    snet = strand_net_names(geo)
    # terminals
    for k, t in enumerate(geo.terminals):
        fid = u()
        members.append(fid)
        net = snet[0]
        clause = " (net %d %s)" % (net_id[net], q(net))
        L.append('  (footprint "LitzGen:LitzTerminal" (layer "F.Cu") (uuid %s) (at %s %s)' % (q(fid), n(t.anchor[0]), n(t.anchor[1])))
        L.append('    (property "Reference" %s (at 0 -3 0) (layer "F.SilkS") (uuid %s) (effects (font (size 1 1) (thickness 0.15))))'
                 % (q("LT%d" % (k + 1)), q(u())))
        L.append('    (property "Value" %s (at 0 3 0) (layer "F.Fab") (uuid %s) (effects (font (size 1 1) (thickness 0.15))))'
                 % (q("%s_%s" % (p.net_prefix, t.name)), q(u())))
        L.append('    (attr board_only exclude_from_pos_files exclude_from_bom)')
        L += ["  " + x for x in _terminal_body(t, clause, t.anchor)]
        L.append('  )')
    lay = st.kicad_layers
    for tr in geo.tracks:
        i = u(); members.append(i)
        net = snet[tr.strand]
        L.append('  (segment (start %s %s) (end %s %s) (width %s) (layer %s) (net %d) (uuid %s))'
                 % (n(tr.start[0]), n(tr.start[1]), n(tr.end[0]), n(tr.end[1]), n(tr.width), q(lay[tr.layer]), net_id[net], q(i)))
    for a in geo.arcs:
        i = u(); members.append(i)
        net = snet[a.strand]
        L.append('  (arc (start %s %s) (mid %s %s) (end %s %s) (width %s) (layer %s) (net %d) (uuid %s))'
                 % (n(a.start[0]), n(a.start[1]), n(a.mid[0]), n(a.mid[1]), n(a.end[0]), n(a.end[1]), n(a.width),
                    q(lay[a.layer]), net_id[net], q(i)))
    for v in geo.vias:
        i = u(); members.append(i)
        net = snet[v.strand]
        lo, hi = sorted((v.la, v.lb))
        through = (lay[lo] == "F.Cu" and lay[hi] == "B.Cu")
        kw = "" if through else " blind"
        L.append('  (via%s (at %s %s) (size %s) (drill %s) (layers %s %s) (net %d) (uuid %s))'
                 % (kw, n(v.pos[0]), n(v.pos[1]), n(v.pad), n(v.drill), q(lay[lo]), q(lay[hi]), net_id[net], q(i)))
    # outline + parameter record
    R = p.d_out / 2.0 + outline_margin
    L.append('  (gr_circle (center %s %s) (end %s %s) (stroke (width 0.1) (type default)) (fill none) (layer "Edge.Cuts") (uuid %s))'
             % (n(p.center_x), n(p.center_y), n(p.center_x + R), n(p.center_y), q(u())))
    if include_params:
        tid = u(); members.append(tid)
        L.append('  (gr_text %s (at %s %s 0) (layer "Cmts.User") (uuid %s) (effects (font (size 0.5 0.5) (thickness 0.08)) (justify left)))'
                 % (q("LITZGEN " + json.dumps(p.to_dict(), separators=(",", ":"))), n(p.center_x - R), n(p.center_y + R + 2), q(tid)))
    L.append('  (group %s (uuid %s) (members %s))' % (q(p.group_name), q(u()), " ".join(q(m) for m in members)))
    L.append(')')
    return "\n".join(L) + "\n"


# ----------------------------------------------------------------------------- minimal S-expression parser (tests)
def parse(text: str):
    """Tiny S-expression parser returning nested lists (used for round-trip tests)."""
    tokens = []
    i, N = 0, len(text)
    while i < N:
        c = text[i]
        if c in "()":
            tokens.append(c); i += 1
        elif c.isspace():
            i += 1
        elif c == '"':
            j = i + 1
            buf = []
            while text[j] != '"':
                if text[j] == "\\":
                    buf.append(text[j + 1]); j += 2
                else:
                    buf.append(text[j]); j += 1
            tokens.append(("s", "".join(buf))); i = j + 1
        else:
            j = i
            while j < N and not text[j].isspace() and text[j] not in "()":
                j += 1
            tokens.append(text[i:j]); i = j
    stack = [[]]
    for t in tokens:
        if t == "(":
            stack.append([])
        elif t == ")":
            done = stack.pop()
            stack[-1].append(done)
        else:
            stack[-1].append(t[1] if isinstance(t, tuple) else t)
    if len(stack) != 1:
        raise ValueError("unbalanced parentheses")
    return stack[0]
